info:
  component: Zuul Server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    test: /test

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
